### ISSUE TITLE
cannot import name lzma

### ISSUE THREAD

**Issue by lanjianchun** [BigNerd95/Chimay-Red#8]
root@kali:~/test/Chimay-Red# proxychains python getROSbin.py 6.37.2 x86 /nova/bin/www www_binary
ProxyChains-3.1 (http://proxychains.sf.net)
|DNS-request| ::1 
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response|: ::1 does not exist
Downloading firmware...
|DNS-request| download2.mikrotik.com 
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response| download2.mikrotik.com is 52.85.158.145
|S-chain|-<>-127.0.0.1:1080-<><>-52.85.158.145:443-<><>-OK
('Extracting', '/nova/bin/www')
cannot import name lzma

how to fix this problem？

**Comment by BigNerd95** [comment]
Maybe related to PySquashfsImage
Try reinstalling it
Or simply download the firmware and extract it using binwalk

**Comment by nanolikeyou** [comment]
I have downloaded  the "routeros-x86-6.27.npk",can I unzip to use the "/nova/bin/www" file as the "www_binary"? i don't understand to use binwalk to get which file.
And, also I get that error:
use mips:
Traceback (most recent call last):
  File "./StackClash_mips.py", line 230, in <module>
    payload = build_payload(binRop, shellCmd)
  File "./StackClash_mips.py", line 127, in build_payload
    stack_finder = binRop.get_gadgets("addiu ?a0, ?sp, 0x18; lw ?ra, 0x???(?sp% jr ?ra;")[0]
  File "./StackClash_mips.py", line 43, in get_gadgets
    raise Exception("Cannot find gadgets!")
Exception: Cannot find gadgets!

use x86:
  File "./StackClash_x86.py", line 232, in <module>
    ropChain = buildROP(binary, shellCmd)
  File "./StackClash_x86.py", line 178, in buildROP
    loadOffsets(binary, shellCmd)
  File "./StackClash_x86.py", line 98, in loadOffsets
    elf = ELF(binary)
  File "/usr/local/lib/python2.7/site-packages/pwnlib/elf/elf.py", line 328, in __init__
    self._populate_libraries()
  File "/usr/local/lib/python2.7/site-packages/pwnlib/elf/elf.py", line 631, in _populate_libraries
    data = subprocess.check_output(cmd, shell = True, stderr = subprocess.STDOUT)
  File "/usr/local/lib/python2.7/subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1205, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
@BigNerd95

**Comment by BigNerd95** [comment]
Any way to extract the file is valid
Only check it is an ELF file once extracted

Mips: it looks like it isnt able to find the gadgets, very strange, which version of ROS are you using?

X86: it looks like a pwntools problem, i cant offer support about this

**Comment by nanolikeyou** [comment]
@BigNerd95 
thanks.the version is 6.27,my test ip is 180.166.152.83
in fact no one target version I test is succesful......

**Comment by BigNerd95** [comment]
I tested it on 6.18, 6.37 and 8.38.3
And it works

Are you sure you are using mipsbe version of www with StackClash_mips?
